-- 코드를 입력하세요
SELECT * FROM (
SELECT T1.CAR_ID, T1.CAR_TYPE, FLOOR(((T1.DAILY_FEE * 30) * (100 - T3.DISCOUNT_RATE)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR T1, CAR_RENTAL_COMPANY_DISCOUNT_PLAN T3
WHERE (T1.CAR_TYPE = '세단' OR T1.CAR_TYPE = 'SUV')
AND (T1.CAR_ID NOT IN (
    SELECT DISTINCT T2.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T2
    WHERE (T2.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD'))
    AND (T2.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD'))
))
AND (T1.CAR_TYPE = T3.CAR_TYPE)
AND (T3.DURATION_TYPE = '30일 이상')
ORDER BY FEE DESC, T1.CAR_TYPE ASC, T1.CAR_ID DESC
)
WHERE (500000 <= FEE AND FEE < 2000000)
;
